// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Path from "path";
import * as Process from "process";
import * as Belt_Result from "rescript/lib/es6/belt_Result.js";
import * as Lib$RescriptStdlibCli from "../Lib.mjs";
import * as ResFile$RescriptStdlibCli from "../entities/ResFile.mjs";
import * as BsConfig$RescriptStdlibCli from "../entities/BsConfig.mjs";
import * as SourceDirs$RescriptStdlibCli from "../entities/SourceDirs.mjs";
import * as LintContext$RescriptStdlibCli from "../entities/LintContext.mjs";

function make(loadBsConfig, loadSourceDirs) {
  var prohibitedModules = [
    "Belt",
    "Js",
    "ReScriptJs"
  ];
  return function () {
    return Belt_Result.flatMap(Belt_Result.flatMap(Belt_Result.flatMap(Lib$RescriptStdlibCli.Result.mapError(loadBsConfig(), (function (loadBsConfigError) {
                              return {
                                      NAME: "BS_CONFIG_PARSE_FAILURE",
                                      VAL: loadBsConfigError.VAL
                                    };
                            })), (function (bsConfig) {
                          return Lib$RescriptStdlibCli.Result.mapError(BsConfig$RescriptStdlibCli.lint(bsConfig, prohibitedModules), (function (error) {
                                        return {
                                                NAME: "BS_CONFIG_HAS_OPENED_PROHIBITED_MODULE",
                                                VAL: error.VAL
                                              };
                                      }));
                        })), (function (param) {
                      return Lib$RescriptStdlibCli.Result.mapError(loadSourceDirs(), (function (loadSourceDirsError) {
                                    return {
                                            NAME: "SOURCE_DIRS_PARSE_FAILURE",
                                            VAL: loadSourceDirsError.VAL
                                          };
                                  }));
                    })), (function (sourceDirs) {
                  var resFiles = SourceDirs$RescriptStdlibCli.getProjectDirs(sourceDirs).flatMap(function (sourceDir) {
                          var fullDirPath = Path.resolve(Process.cwd(), sourceDir);
                          return Fs.readdirSync(fullDirPath).filter(function (dirItem) {
                                        return dirItem.endsWith(".res");
                                      }).map(function (dirItem) {
                                      return "" + fullDirPath + "/" + dirItem + "";
                                    });
                        }).map(function (resFilePath) {
                        return ResFile$RescriptStdlibCli.make(Fs.readFileSync(resFilePath, {
                                          encoding: "utf8"
                                        }).toString(), resFilePath);
                      });
                  var lintContext = LintContext$RescriptStdlibCli.make(undefined);
                  resFiles.forEach(function (resFile) {
                        ResFile$RescriptStdlibCli.lint(resFile, lintContext, prohibitedModules);
                      });
                  var lintIssues = LintContext$RescriptStdlibCli.getIssues(lintContext);
                  if (lintIssues.length !== 0) {
                    return {
                            TAG: /* Error */1,
                            _0: {
                              NAME: "LINT_FAILED_WITH_ISSUES",
                              VAL: lintIssues
                            }
                          };
                  } else {
                    return {
                            TAG: /* Ok */0,
                            _0: undefined
                          };
                  }
                }));
  };
}

export {
  make ,
}
/* fs Not a pure module */
