// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Result from "rescript/lib/es6/belt_Result.js";
import * as Lib$RescriptStdlibCli from "../Lib.mjs";
import * as BsConfig$RescriptStdlibCli from "../BsConfig.mjs";

function make(loadBsConfig) {
  var standardLibModules = [
    "Belt",
    "Js",
    "ReScriptJs"
  ];
  return function () {
    return Belt_Result.flatMap(Lib$RescriptStdlibCli.Result.mapError(loadBsConfig(), (function (loadBsConfigError) {
                      if (typeof loadBsConfigError === "object") {
                        return {
                                NAME: "BS_CONFIG_PARSE_FAILURE",
                                VAL: loadBsConfigError.VAL
                              };
                      } else {
                        return "BS_CONFIG_LOAD_FAILURE";
                      }
                    })), (function (bsconfig) {
                  var globalyOpenedModules = BsConfig$RescriptStdlibCli.globalyOpenedModules(bsconfig);
                  var maybeOpenedStandardLibModule = standardLibModules.find(function (standardLibModule) {
                        return globalyOpenedModules.some(function (globalyOpenedModule) {
                                    return globalyOpenedModule === standardLibModule;
                                  });
                      });
                  if (maybeOpenedStandardLibModule !== undefined) {
                    return {
                            TAG: /* Error */1,
                            _0: {
                              NAME: "HAS_GLOBALY_OPENED_STDLIB",
                              VAL: maybeOpenedStandardLibModule
                            }
                          };
                  } else {
                    return {
                            TAG: /* Ok */0,
                            _0: undefined
                          };
                  }
                }));
  };
}

export {
  make ,
}
/* No side effect */
