// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Path from "path";
import * as Config from "../entities/Config.bs.mjs";
import * as ResFile from "../entities/ResFile.bs.mjs";
import * as BsConfig from "../entities/BsConfig.bs.mjs";
import * as ModuleName from "../entities/ModuleName.bs.mjs";
import * as SourceDirs from "../entities/SourceDirs.bs.mjs";
import * as LintContext from "../entities/LintContext.bs.mjs";
import * as Stdlib_Result from "@dzakh/rescript-stdlib/src/Stdlib_Result.bs.mjs";

function make(loadBsConfig, loadSourceDirs) {
  return function (config) {
    return Stdlib_Result.flatMap(Stdlib_Result.flatMap(Stdlib_Result.flatMap(Stdlib_Result.mapError(loadBsConfig(config), (function (loadBsConfigError) {
                              return {
                                      TAG: /* BsConfigParseFailure */0,
                                      _0: loadBsConfigError._0
                                    };
                            })), (function (bsConfig) {
                          var match = BsConfig.lint(bsConfig, ModuleName.defaultProhibitedModuleNames);
                          if (match.TAG === /* Ok */0) {
                            return {
                                    TAG: /* Ok */0,
                                    _0: bsConfig
                                  };
                          } else {
                            return {
                                    TAG: /* Error */1,
                                    _0: {
                                      TAG: /* BsConfigHasOpenedProhibitedModule */2,
                                      _0: match._0.VAL
                                    }
                                  };
                          }
                        })), (function (bsConfig) {
                      var sourceDirs = loadSourceDirs(config);
                      if (sourceDirs.TAG === /* Ok */0) {
                        return {
                                TAG: /* Ok */0,
                                _0: [
                                  bsConfig,
                                  sourceDirs._0
                                ]
                              };
                      }
                      var loadSourceDirsError = sourceDirs._0;
                      return {
                              TAG: /* Error */1,
                              _0: loadSourceDirsError ? ({
                                    TAG: /* SourceDirsParseFailure */1,
                                    _0: loadSourceDirsError._0
                                  }) : /* RescriptCompilerArtifactsNotFound */0
                            };
                    })), (function (param) {
                  var bsConfig = param[0];
                  var resFiles = SourceDirs.getProjectDirs(param[1]).flatMap(function (sourceDir) {
                        var fullDirPath = Path.resolve(Config.getProjectPath(config), sourceDir);
                        return Fs.readdirSync(fullDirPath).filter(ResFile.checkIsResFile).map(function (dirItem) {
                                    var resFilePath = "" + fullDirPath + "/" + dirItem + "";
                                    return ResFile.make(Fs.readFileSync(resFilePath, {
                                                      encoding: "utf8"
                                                    }).toString(), resFilePath);
                                  });
                      });
                  var lintContext = LintContext.make(undefined);
                  resFiles.forEach(function (resFile) {
                        ResFile.lint(resFile, lintContext, ModuleName.defaultProhibitedModuleNames, Config.getStdlibModuleName(config), Config.checkShouldIngoreResFileIssuesBeforeStdlibOpen(config, bsConfig));
                      });
                  var lintIssues = LintContext.getIssues(lintContext);
                  if (lintIssues.length !== 0) {
                    return {
                            TAG: /* Error */1,
                            _0: {
                              TAG: /* LintFailedWithIssues */3,
                              _0: lintIssues
                            }
                          };
                  } else {
                    return {
                            TAG: /* Ok */0,
                            _0: undefined
                          };
                  }
                }));
  };
}

export {
  make ,
}
/* fs Not a pure module */
