// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Path from "path";
import * as Process from "process";
import * as BsConfig from "../entities/BsConfig.mjs";
import * as Stdlib_Result from "stdlib/src/Stdlib_Result.mjs";
import * as S$ReScriptStruct from "rescript-struct/src/S.mjs";

function make(param) {
  return function () {
    var jsonObj = JSON.parse(Fs.readFileSync(Path.resolve(Process.cwd(), "bsconfig.json"), {
                encoding: "utf8"
              }).toString());
    return Stdlib_Result.mapError(S$ReScriptStruct.parseWith(jsonObj, BsConfig.struct), (function (error) {
                  return /* ParsingFailure */{
                          _0: S$ReScriptStruct.$$Error.toString(error)
                        };
                }));
  };
}

export {
  make ,
}
/* fs Not a pure module */
