// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Path from "path";
import * as Config from "../entities/Config.bs.mjs";
import * as SourceDirs from "../entities/SourceDirs.bs.mjs";
import * as Stdlib_Result from "@dzakh/rescript-stdlib/src/Stdlib_Result.bs.mjs";

function make(param) {
  return function (config) {
    var tmp;
    try {
      tmp = {
        TAG: /* Ok */0,
        _0: Fs.readFileSync(Path.resolve(Config.getProjectPath(config), "lib/bs/.sourcedirs.json"), {
                encoding: "utf8"
              }).toString()
      };
    }
    catch (exn){
      tmp = {
        TAG: /* Error */1,
        _0: /* RescriptCompilerArtifactsNotFound */0
      };
    }
    return Stdlib_Result.flatMap(tmp, (function (file) {
                  return Stdlib_Result.mapError(SourceDirs.fromJsonString(file), (function (error) {
                                return /* ParsingFailure */{
                                        _0: error
                                      };
                              }));
                }));
  };
}

export {
  make ,
}
/* fs Not a pure module */
