// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Path from "path";
import * as Config from "../entities/Config.bs.mjs";
import * as Stdlib from "@dzakh/rescript-stdlib/src/Stdlib.bs.mjs";
import * as BsConfig from "../entities/BsConfig.bs.mjs";

function make() {
  return function (config) {
    return Stdlib.Result.mapError(BsConfig.fromJsonString(Fs.readFileSync(Path.resolve(Config.getProjectPath(config), "bsconfig.json"), {
                          encoding: "utf8"
                        }).toString()), (function (error) {
                  return {
                          TAG: "ParsingFailure",
                          _0: error
                        };
                }));
  };
}

export {
  make ,
}
/* fs Not a pure module */
