// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Config from "../entities/Config.bs.mjs";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Stdlib from "@dzakh/rescript-stdlib/src/Stdlib.bs.mjs";
import * as Process from "process";
import Minimist from "minimist";
import * as S$RescriptStruct from "rescript-struct/src/S.bs.mjs";

function make(runLintCommand, runHelpCommand, runHelpLintCommand, exitConsoleWithError) {
  return function () {
    var commandArguments = Process.argv.slice(2);
    var result = Stdlib.Result.map(Stdlib.Result.mapError(S$RescriptStruct.parseWith(Minimist(commandArguments), S$RescriptStruct.union([
                      S$RescriptStruct.$$Object.strict(S$RescriptStruct.object(function (o) {
                                S$RescriptStruct.field(o, "_", S$RescriptStruct.union([
                                          S$RescriptStruct.tuple0(undefined),
                                          S$RescriptStruct.tuple1(S$RescriptStruct.literalVariant({
                                                    TAG: "String",
                                                    _0: "help"
                                                  }, undefined))
                                        ]));
                                return "Help";
                              })),
                      S$RescriptStruct.$$Object.strict(S$RescriptStruct.object(function (o) {
                                S$RescriptStruct.field(o, "_", S$RescriptStruct.tuple2(S$RescriptStruct.literal({
                                              TAG: "String",
                                              _0: "help"
                                            }), S$RescriptStruct.literal({
                                              TAG: "String",
                                              _0: "lint"
                                            })));
                                return "LintHelp";
                              })),
                      S$RescriptStruct.$$Object.strict(S$RescriptStruct.object(function (o) {
                                S$RescriptStruct.field(o, "_", S$RescriptStruct.tuple1(S$RescriptStruct.literal({
                                              TAG: "String",
                                              _0: "lint"
                                            })));
                                return {
                                        TAG: "Lint",
                                        _0: Config.make(S$RescriptStruct.field(o, "project-path", S$RescriptStruct.$$default(S$RescriptStruct.option(S$RescriptStruct.string(undefined)), (function () {
                                                        return Process.cwd();
                                                      }))), S$RescriptStruct.field(o, "ignore-without-stdlib-open", S$RescriptStruct.$$default(S$RescriptStruct.option(S$RescriptStruct.bool(undefined)), (function () {
                                                        return false;
                                                      }))), S$RescriptStruct.field(o, "ignore-path", S$RescriptStruct.$$default(S$RescriptStruct.option(S$RescriptStruct.union([
                                                              S$RescriptStruct.transform(S$RescriptStruct.string(undefined), (function (s) {
                                                                      return [s];
                                                                    }), undefined, undefined, undefined),
                                                              S$RescriptStruct.array(S$RescriptStruct.string(undefined))
                                                            ])), (function () {
                                                        return [];
                                                      }))))
                                      };
                              }))
                    ])), (function (error) {
                var unionErrors = error.code;
                if (typeof unionErrors !== "object") {
                  return Js_exn.raiseError("Parsed error always must have the InvalidUnion code");
                }
                if (unionErrors.TAG !== "InvalidUnion") {
                  return Js_exn.raiseError("Parsed error always must have the InvalidUnion code");
                }
                var maybeIllegalOptionName = Stdlib.$$Option.map(unionErrors._0.find(function (error) {
                          var match = error.code;
                          if (typeof match !== "object" || match.TAG !== "ExcessField") {
                            return false;
                          } else {
                            return true;
                          }
                        }), (function (excessFieldError) {
                        var illegalOptionName = excessFieldError.code;
                        if (typeof illegalOptionName !== "object" || illegalOptionName.TAG !== "ExcessField") {
                          return Js_exn.raiseError("The excessFieldError always must have the ExcessField code");
                        } else {
                          return illegalOptionName._0;
                        }
                      }));
                if (maybeIllegalOptionName !== undefined) {
                  return {
                          TAG: "IllegalOption",
                          optionName: maybeIllegalOptionName
                        };
                } else {
                  return "CommandNotFound";
                }
              })), (function (command) {
            if (typeof command !== "object") {
              if (command === "Help") {
                return runHelpCommand(undefined);
              } else {
                return runHelpLintCommand(undefined);
              }
            } else {
              return runLintCommand(command._0);
            }
          }));
    if (result.TAG === "Ok") {
      return ;
    }
    var error = result._0;
    if (typeof error !== "object") {
      return exitConsoleWithError("Command not found: " + commandArguments.join(" "));
    } else {
      return exitConsoleWithError("Illegal option: " + error.optionName);
    }
  };
}

export {
  make ,
}
/* Config Not a pure module */
