// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "rescript-struct/src/S.mjs";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Process from "process";
import Minimist from "minimist";
import * as LintIssue from "../entities/LintIssue.mjs";
import * as Colorette from "colorette";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Stdlib_Result from "../stdlib/Stdlib_Result.mjs";

function make(runLintCommand, runHelpCommand, runLintHelpCommand) {
  return function () {
    var commandArguments = Process.argv.slice(2);
    var result = Stdlib_Result.flatMap(Stdlib_Result.mapError(S.parseWith(Minimist(commandArguments), S.union([
                      S.transform(S.$$Object.strict(S.object1([
                                    "_",
                                    S.union([
                                          S.tuple0(),
                                          S.tuple1(S.literalVariant({
                                                    TAG: /* String */0,
                                                    _0: "help"
                                                  }, undefined))
                                        ])
                                  ])), (function (param) {
                              return /* Help */0;
                            }), undefined, undefined),
                      S.transform(S.$$Object.strict(S.object1([
                                    "_",
                                    S.tuple2(S.literalVariant({
                                              TAG: /* String */0,
                                              _0: "help"
                                            }, undefined), S.literalVariant({
                                              TAG: /* String */0,
                                              _0: "lint"
                                            }, undefined))
                                  ])), (function (param) {
                              return /* LintHelp */2;
                            }), undefined, undefined),
                      S.transform(S.$$Object.strict(S.object1([
                                    "_",
                                    S.tuple1(S.literalVariant({
                                              TAG: /* String */0,
                                              _0: "lint"
                                            }, undefined))
                                  ])), (function (param) {
                              return /* Lint */1;
                            }), undefined, undefined)
                    ])), (function (error) {
                var unionErrors = error.code;
                if (typeof unionErrors === "number") {
                  return Js_exn.raiseError("Parsed error always must have the InvalidUnion code");
                }
                if (unionErrors.TAG !== /* InvalidUnion */5) {
                  return Js_exn.raiseError("Parsed error always must have the InvalidUnion code");
                }
                var maybeIllegalOptionName = Belt_Option.map(Caml_option.undefined_to_opt(unionErrors._0.find(function (error) {
                              var match = error.code;
                              if (typeof match === "number" || match.TAG !== /* ExcessField */4) {
                                return false;
                              } else {
                                return true;
                              }
                            })), (function (excessFieldError) {
                        var illegalOptionName = excessFieldError.code;
                        if (typeof illegalOptionName === "number" || illegalOptionName.TAG !== /* ExcessField */4) {
                          return Js_exn.raiseError("The excessFieldError always must have the ExcessField code");
                        } else {
                          return illegalOptionName._0;
                        }
                      }));
                if (maybeIllegalOptionName !== undefined) {
                  return {
                          TAG: /* IllegalOption */0,
                          optionName: maybeIllegalOptionName
                        };
                } else {
                  return /* CommandNotFound */0;
                }
              })), (function (command) {
            switch (command) {
              case /* Help */0 :
                  return {
                          TAG: /* Ok */0,
                          _0: runHelpCommand()
                        };
              case /* Lint */1 :
                  return Stdlib_Result.mapError(runLintCommand(), (function (lintCommandError) {
                                return {
                                        TAG: /* LintCommandError */1,
                                        _0: lintCommandError
                                      };
                              }));
              case /* LintHelp */2 :
                  return {
                          TAG: /* Ok */0,
                          _0: runLintHelpCommand()
                        };
              
            }
          }));
    if (result.TAG === /* Ok */0) {
      return ;
    }
    var error = result._0;
    if (typeof error === "number") {
      console.log("Command not found:", commandArguments.join(" "));
    } else if (error.TAG === /* IllegalOption */0) {
      console.log("Illegal option:", error.optionName);
    } else {
      var match = error._0;
      var variant = match.NAME;
      if (variant === "BS_CONFIG_HAS_OPENED_PROHIBITED_MODULE") {
        console.log("Lint failed: Found globally opened module " + match.VAL + "");
      } else if (variant === "LINT_FAILED_WITH_ISSUES") {
        match.VAL.forEach(function (lintIssue) {
              console.log(Colorette.underline(LintIssue.getLink(lintIssue)), "\n", LintIssue.getMessage(lintIssue), "\n");
            });
        console.log(Colorette.bold("Use your custom standard library instead."));
      } else if (variant === "BS_CONFIG_PARSE_FAILURE") {
        console.log("Failed to parse \"bsconfig.json\":", match.VAL);
      } else {
        console.log("Failed to parse \".sourcedirs.json\". Check that you use compatible ReScript version. Parsing error:", match.VAL);
      }
    }
    Process.exit(1);
  };
}

export {
  make ,
}
/* process Not a pure module */
