// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Colorette from "colorette";

function make(param) {
  return function () {
    console.log([
            "",
            "Available commands are:",
            "",
            "* " + Colorette.bold("help") + " - Display this message",
            "* " + Colorette.bold("help <command>") + " - Show more information about a command",
            "* " + Colorette.bold("lint") + " - Lint rescript standard libriries usage",
            "",
            "You can find more information about the reasoning behind the tool in the documentation: " + Colorette.underline("https://github.com/DZakh/rescript-stdlib-lint") + "",
            ""
          ].join("\n"));
  };
}

export {
  make ,
}
/* colorette Not a pure module */
