// Generated by ReScript, PLEASE EDIT WITH CARE


function make(param) {
  return function () {
    console.log([
            "",
            "Lint rescript standard libriries usage.",
            ""
          ].join("\n"));
  };
}

export {
  make ,
}
/* No side effect */
