// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "rescript-struct/src/S.mjs";

function getGlobalyOpenedModules(bsConfig) {
  return bsConfig.bscFlags.filter(function (bscFlag) {
                return bscFlag.includes("-open");
              }).map(function (bscFlag) {
              return bscFlag.replace("-open", "").trim().split(".")[0];
            });
}

var struct = S.transform(S.object1([
          "bsc-flags",
          S.defaulted(S.option(S.array(S.string(undefined))), [])
        ]), (function (bscFlags) {
        return {
                bscFlags: bscFlags
              };
      }), undefined, undefined);

export {
  getGlobalyOpenedModules ,
  struct ,
}
/* struct Not a pure module */
