// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S$ReScriptStruct from "rescript-struct/src/S.bs.mjs";

function getGlobalyOpenedModules(bsConfig) {
  return bsConfig.bscFlags.filter(function (bscFlag) {
                return bscFlag.includes("-open");
              }).map(function (bscFlag) {
              return bscFlag.replace("-open", "").trim().split(".")[0];
            });
}

function lint(bsConfig, prohibitedModuleNames) {
  var globalyOpenedModules = getGlobalyOpenedModules(bsConfig);
  var maybeOpenedProhibitedModule = prohibitedModuleNames.find(function (prohibitedModule) {
        return globalyOpenedModules.some(function (globalyOpenedModule) {
                    return globalyOpenedModule === prohibitedModule;
                  });
      });
  if (maybeOpenedProhibitedModule !== undefined) {
    return {
            TAG: /* Error */1,
            _0: {
              NAME: "HAS_OPENED_PROHIBITED_MODULE",
              VAL: maybeOpenedProhibitedModule
            }
          };
  } else {
    return {
            TAG: /* Ok */0,
            _0: undefined
          };
  }
}

var struct = S$ReScriptStruct.object(function (o) {
      return {
              bscFlags: S$ReScriptStruct.field(o, "bsc-flags", S$ReScriptStruct.defaulted(S$ReScriptStruct.option(S$ReScriptStruct.array(S$ReScriptStruct.string(undefined))), []))
            };
    });

export {
  lint ,
  struct ,
}
/* struct Not a pure module */
