// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ResConfig from "./ResConfig.bs.mjs";
import * as ModuleName from "./ModuleName.bs.mjs";

function make(projectPath, ignoreWithoutStdlibOpen, ignorePaths) {
  return {
          projectPath: projectPath,
          ignoreWithoutStdlibOpen: ignoreWithoutStdlibOpen,
          stdlibModuleName: ModuleName.defaultStdlibModuleName,
          ignorePaths: ignorePaths
        };
}

function getProjectPath(config) {
  return config.projectPath;
}

function getStdlibModuleName(config) {
  return config.stdlibModuleName;
}

function checkShouldIngoreResFileIssuesBeforeStdlibOpen(config, resConfig) {
  if (config.ignoreWithoutStdlibOpen) {
    return !ResConfig.hasGloballyOpenedModule(resConfig, config.stdlibModuleName);
  } else {
    return false;
  }
}

function checkIsIgnoredPath(config, relativePath) {
  return config.ignorePaths.some(function (ignorePath) {
              return relativePath.startsWith(ignorePath);
            });
}

export {
  make ,
  getProjectPath ,
  getStdlibModuleName ,
  checkShouldIngoreResFileIssuesBeforeStdlibOpen ,
  checkIsIgnoredPath ,
}
/* ResConfig Not a pure module */
