// Generated by ReScript, PLEASE EDIT WITH CARE


function make(projectPath) {
  return {
          projectPath: projectPath
        };
}

function getProjectPath(config) {
  return config.projectPath;
}

export {
  make ,
  getProjectPath ,
}
/* No side effect */
