// Generated by ReScript, PLEASE EDIT WITH CARE


function make(path, kind) {
  return {
          path: path,
          kind: kind
        };
}

function getLink(lintIssue) {
  var match = lintIssue.kind;
  if (match.TAG === /* InvalidStdlibParentDirName */4) {
    return lintIssue.path;
  } else {
    return "" + lintIssue.path + ":" + match.line.toString() + "";
  }
}

function getMessage(lintIssue) {
  var match = lintIssue.kind;
  switch (match.TAG | 0) {
    case /* ProhibitedModuleOpen */0 :
        return "Found \"" + match.prohibitedModuleName + "\" module open.";
    case /* ProhibitedModuleInclude */1 :
        return "Found \"" + match.prohibitedModuleName + "\" module include.";
    case /* ProhibitedModuleAssign */2 :
    case /* ProhibitedModuleUsage */3 :
        return "Found \"" + match.prohibitedModuleName + "\" module usage.";
    case /* InvalidStdlibParentDirName */4 :
        return "The \"" + match.stdlibParentDirName + "\" is an invalid directory name for custom standary library related files. Put the files to the directory with the name \"stdlib\" to make it easier to find them.";
    
  }
}

export {
  make ,
  getLink ,
  getMessage ,
}
/* No side effect */
