// Generated by ReScript, PLEASE EDIT WITH CARE


function make() {
  return [];
}

function addIssue(lintContext, lintIssue) {
  lintContext.push(lintIssue);
}

function getIssues(lintContext) {
  return lintContext;
}

export {
  make ,
  addIssue ,
  getIssues ,
}
/* No side effect */
