// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Result from "@dzakh/rescript-core/src/Core__Result.bs.mjs";
import * as S$RescriptStruct from "rescript-struct/src/S.bs.mjs";

function getProjectDirs(projectDirs) {
  return projectDirs;
}

var struct = S$RescriptStruct.object(function (s) {
      return s.f("dirs", S$RescriptStruct.array(S$RescriptStruct.string));
    });

function fromJsonString(jsonString) {
  return Core__Result.mapError(S$RescriptStruct.parseJsonStringWith(jsonString, struct), S$RescriptStruct.$$Error.message);
}

function make(projectDirs) {
  return projectDirs;
}

var TestData = {
  make: make
};

export {
  getProjectDirs ,
  fromJsonString ,
  TestData ,
}
/* struct Not a pure module */
