// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "rescript-struct/src/S.mjs";

function getProjectDirs(sourceDirs) {
  return sourceDirs;
}

var struct = S.object1([
      "dirs",
      S.array(S.string(undefined))
    ]);

export {
  getProjectDirs ,
  struct ,
}
/* struct Not a pure module */
