// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S$RescriptStruct from "rescript-struct/src/S.bs.mjs";

function getProjectDirs(projectDirs) {
  return projectDirs;
}

var struct = S$RescriptStruct.object(function (o) {
      return S$RescriptStruct.field(o, "dirs", S$RescriptStruct.array(S$RescriptStruct.string(undefined)));
    });

function fromJsonString(jsonString) {
  return S$RescriptStruct.Result.mapErrorToString(S$RescriptStruct.parseJsonWith(jsonString, struct));
}

function make(projectDirs) {
  return projectDirs;
}

var TestData = {
  make: make
};

export {
  getProjectDirs ,
  fromJsonString ,
  TestData ,
}
/* struct Not a pure module */
