// Generated by ReScript, PLEASE EDIT WITH CARE


function make(dir, subdirs) {
  return {
          dir: dir,
          subdirs: subdirs
        };
}

var Source = {
  make: make
};

function make$1(sources, bscFlags) {
  return {
          sources: sources,
          bscFlags: bscFlags
        };
}

function globalyOpenedModules(bsConfig) {
  return bsConfig.bscFlags.filter(function (bscFlag) {
                return bscFlag.includes("-open");
              }).map(function (bscFlag) {
              return bscFlag.replace("-open", "").trim().split(".")[0];
            });
}

export {
  Source ,
  make$1 as make,
  globalyOpenedModules ,
}
/* No side effect */
