// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RunCli from "./interactors/RunCli.mjs";
import * as LoadBsConfig from "./interactors/LoadBsConfig.mjs";
import * as LoadSourceDirs from "./interactors/LoadSourceDirs.mjs";
import * as RunLintCommand from "./interactors/RunLintCommand.mjs";

var runCli = RunCli.make(RunLintCommand.make(LoadBsConfig.make(undefined), LoadSourceDirs.make(undefined)), (function () {
        console.log("Help");
      }), (function () {
        console.log("Lint help");
      }));

runCli();

export {
  runCli ,
}
/* runCli Not a pure module */
