// Generated by ReScript, PLEASE EDIT WITH CARE


function mapError(result, fn) {
  if (result.TAG === /* Ok */0) {
    return result;
  } else {
    return {
            TAG: /* Error */1,
            _0: fn(result._0)
          };
  }
}

var Result = {
  mapError: mapError
};

var $$Array = {};

export {
  Result ,
  $$Array ,
}
/* No side effect */
