// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RunCliService$RescriptStdlibCli from "./services/RunCliService.mjs";
import * as LoadBsConfigService$RescriptStdlibCli from "./services/LoadBsConfigService.mjs";
import * as RunLintCommandService$RescriptStdlibCli from "./services/RunLintCommandService.mjs";

var runCli = RunCliService$RescriptStdlibCli.make(RunLintCommandService$RescriptStdlibCli.make(LoadBsConfigService$RescriptStdlibCli.make(undefined)), (function () {
        console.log("Help");
      }), (function () {
        console.log("Lint help");
      }));

runCli();

export {
  runCli ,
}
/* runCli Not a pure module */
