// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RunCliService$RescriptStdlibCli from "./interactors/RunCliService.mjs";
import * as LoadBsConfigService$RescriptStdlibCli from "./interactors/LoadBsConfigService.mjs";
import * as LoadSourceDirsService$RescriptStdlibCli from "./interactors/LoadSourceDirsService.mjs";
import * as RunLintCommandService$RescriptStdlibCli from "./interactors/RunLintCommandService.mjs";

var runCli = RunCliService$RescriptStdlibCli.make(RunLintCommandService$RescriptStdlibCli.make(LoadBsConfigService$RescriptStdlibCli.make(undefined), LoadSourceDirsService$RescriptStdlibCli.make(undefined)), (function () {
        console.log("Help");
      }), (function () {
        console.log("Lint help");
      }));

runCli();

export {
  runCli ,
}
/* runCli Not a pure module */
