// Generated by ReScript, PLEASE EDIT WITH CARE


var Lint = {};

var RunLintCommand = {};

var RunHelpLintCommand = {};

var RunHelpCommand = {};

var LoadResConfig = {};

var LoadSourceDirs = {};

var RunCli = {};

var ExitConsoleWithError = {};

export {
  Lint ,
  RunLintCommand ,
  RunHelpLintCommand ,
  RunHelpCommand ,
  LoadResConfig ,
  LoadSourceDirs ,
  RunCli ,
  ExitConsoleWithError ,
}
/* No side effect */
