// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Result from "rescript/lib/es6/belt_Result.js";

var flatMap = Belt_Result.flatMapU;

function mapError(result, fn) {
  if (result.TAG === /* Ok */0) {
    return result;
  } else {
    return {
            TAG: /* Error */1,
            _0: fn(result._0)
          };
  }
}

var Result = {
  flatMap: flatMap,
  mapError: mapError
};

var $$Array = {};

var $$String;

var $$Option;

var Exn;

var Json;

var Re;

var Int;

export {
  Result ,
  $$Array ,
  $$String ,
  $$Option ,
  Exn ,
  Json ,
  Re ,
  Int ,
}
/* No side effect */
